[programs.localnet]
gamba = "HaSj7pdndQD9DepFmPrcyL7exQ1BDUfr1qG4Uaxypfa9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/geoffgolder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
